apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user-virtual-service #self explanatory
  namespace: default #self explanatory
spec:
  hosts: # a virtual service can redirect requests for multiple hosts. this is more of a filtering hosts
    - user.microservice.retailvoice.xyz
  gateways: # a virtual service can also received requests from multiple gateway
    - ingressgateway
  http:
    #   it actually saying when I get any requests for user.microservice.retailvoice.xyz,
    #   just redirect it to user-service.default.svc.cluster.local on port 8000
    #   if only one port configuration present in user-service.default.svc.cluster.local then
    #   you can omit the port configuration portion
    - route:
        - destination:
            host: user-service.default.svc.cluster.local
            port:
              number: 8000